# -*- coding: utf-8 -*-
"""
全部中文文献种子词典最终清理
过滤噪声 + 修正类型 + 删除非COPD术语
"""

import os
import json
import re

INPUT_TSV = r"I:\101实验专题\种子词典构建结果\27_全部中文文献_最终种子词典_含类型.tsv"
OUTPUT_DIR = r"I:\101实验专题\种子词典构建结果"

# ========== 明确垃圾黑名单 ==========
BLACKLIST = {
    # PDF编码噪声
    'cid',
    # 截断词
    '否存', '的诊断', '有助', '有利', '慢性咳', '慢阻肺的发生',
    '细胞', '作用', '证据', '治法', '加减', '可待', '检查',
    '其主要症状', '唯一症状', '临床表现', '症治疗', '慢性咳嗽的病',
    '慢性咳嗽的常见病', '刺激性干咳', '常见病',
    # 非COPD核心术语
    '温病条辨', 'Asthma', 'AET', 'CXCL-', 'cells/μL',
    '方药举例', '肺炎球菌', '流感嗜血杆菌',
    # 噪声
    'Lt',
    # 已有中文对应词的英文
    'GERC',  # 已有胃食管反流病
    'UACS/PNDS',  # 已有上气道咳嗽综合征
}

# 类型修正映射
TYPE_FIX = {
    'GERC': 'Disease',
    'ACEI': 'Medication',
    'CVA': 'Disease',
    'PNDS': 'Disease',
    'EB': 'Disease',
    'FeNO': 'Examination',
    'UACS': 'Disease',
    'AECOPD': 'Disease',
    'GOLD': 'Guideline',
    'mMRC': 'Guideline',
    'CAT': 'Guideline',
    'SGRQ': 'Guideline',
    'CCQ': 'Guideline',
    'COPD': 'Disease',
    'ICS': 'Medication',
    'LABA': 'Medication',
    'LAMA': 'Medication',
    'SABA': 'Medication',
    'SAMA': 'Medication',
    'NAC': 'Medication',
    'NPPV': 'Treatment',
    'LVRS': 'Treatment',
    'OSA': 'Complication',
    'OSAHS': 'Complication',
    'PH': 'Complication',
    'PAH': 'Complication',
    'BMI': 'Examination',
    'CT': 'Examination',
    'FEV': 'Examination',
    'FVC': 'Examination',
    'FEV1': 'Examination',
    'FEV1/FVC': 'Examination',
    'DLCO': 'Examination',
    '6MWD': 'Examination',
    '6MWT': 'Examination',
    'PaO2': 'Examination',
    'PaCO2': 'Examination',
    'SpO2': 'Examination',
    'SaO2': 'Examination',
    'CRP': 'Examination',
    'PCT': 'Examination',
    'ESR': 'Examination',
    'BNP': 'Examination',
    'NT-proBNP': 'Examination',
    'D-Dimer': 'Examination',
    'D-二聚体': 'Examination',
    '罗氟司特': 'Medication',
    '阿奇霉素': 'Medication',
    '度普利尤单抗': 'Medication',
    '恩塞芬汀': 'Medication',
    'N-乙酰半胱氨酸': 'Medication',
    '乙酰半胱氨酸': 'Medication',
    '羧甲司坦': 'Medication',
    '沙丁胺醇': 'Medication',
    '特布他林': 'Medication',
    '异丙托溴铵': 'Medication',
    '噻托溴铵': 'Medication',
    '氟替卡松': 'Medication',
    '布地奈德': 'Medication',
    '福莫特罗': 'Medication',
    '茚达特罗': 'Medication',
    '维兰特罗': 'Medication',
    '格隆溴铵': 'Medication',
    '乌美溴铵': 'Medication',
    '阿地溴铵': 'Medication',
    '糠酸氟替卡松': 'Medication',
    '奥达特罗': 'Medication',
    '茶碱': 'Medication',
    '氨茶碱': 'Medication',
    '多索茶碱': 'Medication',
    '苏子降气丸': 'Medication',
    '益肺灸': 'Treatment',
    '舒肺贴': 'Treatment',
    '宣肺止咳': 'Treatment',
    '益气养阴': 'Treatment',
    '健脾益肺': 'Treatment',
    '补肺益肾': 'Treatment',
    '活血化瘀': 'Treatment',
    '清热化痰': 'Treatment',
    '温肺化饮': 'Treatment',
    '温肺散寒': 'Treatment',
    '扶正固本': 'Treatment',
    '扶正祛邪': 'Treatment',
    '冬病夏治': 'Treatment',
    '穴位贴敷': 'Treatment',
    '穴位注射': 'Treatment',
    '水针': 'Treatment',
    '针刺': 'Treatment',
    '电针': 'Treatment',
    '耳针': 'Treatment',
    '头针': 'Treatment',
    '腹针': 'Treatment',
    '腕踝针': 'Treatment',
    '眼针': 'Treatment',
    '鼻针': 'Treatment',
    '舌针': 'Treatment',
    '手针': 'Treatment',
    '足针': 'Treatment',
    '皮内针': 'Treatment',
    '梅花针': 'Treatment',
    '七星针': 'Treatment',
    '皮肤针': 'Treatment',
    '挑刺': 'Treatment',
    '放血': 'Treatment',
    '刺络': 'Treatment',
    '割治': 'Treatment',
    '埋线': 'Treatment',
    '磁疗': 'Treatment',
    '光疗': 'Treatment',
    '超声波': 'Treatment',
    '红外线': 'Treatment',
    'TDP': 'Treatment',
    '神灯': 'Treatment',
    '熏蒸': 'Treatment',
    '药浴': 'Treatment',
    '足浴': 'Treatment',
    '药枕': 'Treatment',
    '药熨': 'Treatment',
    '药栓': 'Treatment',
    '药膜': 'Treatment',
    '药膏': 'Treatment',
    '药酒': 'Treatment',
    '药膳': 'Treatment',
    '八段锦': 'Treatment',
    '五禽戏': 'Treatment',
    '太极拳': 'Treatment',
    '太极': 'Treatment',
    '易筋经': 'Treatment',
    '六字诀': 'Treatment',
    '导引术': 'Treatment',
    '调息': 'Treatment',
    '静坐': 'Treatment',
    '冥想': 'Treatment',
    '放松训练': 'Treatment',
    '呼吸训练': 'Treatment',
    '缩唇呼吸': 'Treatment',
    '腹式呼吸': 'Treatment',
    '膈肌呼吸': 'Treatment',
    '呼吸操': 'Treatment',
    '呼吸肌训练': 'Treatment',
    '吸气肌训练': 'Treatment',
    '排痰训练': 'Treatment',
    '有效咳嗽': 'Treatment',
    '体位引流': 'Treatment',
    '胸部叩击': 'Treatment',
    '胸部振动': 'Treatment',
    '气道廓清': 'Treatment',
    '高频胸壁振荡': 'Treatment',
    '机械吸排气': 'Treatment',
    '肺内振荡': 'Treatment',
    '运动训练': 'Treatment',
    '有氧训练': 'Treatment',
    '抗阻训练': 'Treatment',
    '耐力训练': 'Treatment',
    '柔韧性训练': 'Treatment',
    '步行训练': 'Treatment',
    '踏车训练': 'Treatment',
    '上肢训练': 'Treatment',
    '下肢训练': 'Treatment',
    '核心训练': 'Treatment',
    '平衡训练': 'Treatment',
    '协调训练': 'Treatment',
    '神经肌肉电刺激': 'Treatment',
    '功能性电刺激': 'Treatment',
    '经颅磁刺激': 'Treatment',
    '经颅直流电刺激': 'Treatment',
    '生物反馈': 'Treatment',
    '虚拟现实': 'Treatment',
    '远程康复': 'Treatment',
    '居家康复': 'Treatment',
    '社区康复': 'Treatment',
    '门诊康复': 'Treatment',
    '住院康复': 'Treatment',
    '急性期康复': 'Treatment',
    '稳定期康复': 'Treatment',
    '恢复期康复': 'Treatment',
    '维持期康复': 'Treatment',
    '一级预防': 'Treatment',
    '二级预防': 'Treatment',
    '三级预防': 'Treatment',
    '健康宣教': 'Treatment',
    '患者教育': 'Treatment',
    '自我管理': 'Treatment',
    '疾病认知': 'Treatment',
    '用药依从性': 'Treatment',
    '吸入技术': 'Treatment',
    '装置使用': 'Treatment',
    '储雾罐': 'Treatment',
    ' spacer ': 'Treatment',
    '雾化器': 'Treatment',
    '干粉吸入器': 'Treatment',
    'DPI': 'Treatment',
    '压力定量吸入器': 'Treatment',
    'pMDI': 'Treatment',
    '软雾吸入器': 'Treatment',
    'SMI': 'Treatment',
    ' Breath-actuated ': 'Treatment',
    'nebulizer': 'Treatment',
    'compressor': 'Treatment',
    '家庭氧疗': 'Treatment',
    '便携氧疗': 'Treatment',
    '夜间氧疗': 'Treatment',
    '运动氧疗': 'Treatment',
    '高流量氧疗': 'Treatment',
    'HFNC': 'Treatment',
    '经鼻高流量': 'Treatment',
    '气管插管': 'Treatment',
    '气管切开': 'Treatment',
    '呼吸机': 'Treatment',
    '撤机': 'Treatment',
    '脱机': 'Treatment',
    ' weaning': 'Treatment',
    '单向活瓣': 'Treatment',
    '弹簧圈': 'Treatment',
    '生物胶': 'Treatment',
    '热蒸汽消融': 'Treatment',
    '靶向肺去神经': 'Treatment',
    '心脏康复': 'Treatment',
    '运动处方': 'Treatment',
    '免疫营养': 'Treatment',
    '精准营养': 'Treatment',
    '高蛋白饮食': 'Treatment',
    '低碳水饮食': 'Treatment',
    '地中海饮食': 'Treatment',
    'DASH饮食': 'Treatment',
    '抗炎饮食': 'Treatment',
    '抗氧化饮食': 'Treatment',
    '益生菌': 'Treatment',
    '益生元': 'Treatment',
    '合生元': 'Treatment',
    '肠道菌群': 'Treatment',
    '微生态': 'Treatment',
    '粪菌移植': 'Treatment',
    'FMT': 'Treatment',
    '心理干预': 'Treatment',
    '认知行为治疗': 'Treatment',
    'CBT': 'Treatment',
    '正念减压': 'Treatment',
    'MBSR': 'Treatment',
    '团体治疗': 'Treatment',
    '家庭治疗': 'Treatment',
    '音乐治疗': 'Treatment',
    '艺术治疗': 'Treatment',
    '园艺治疗': 'Treatment',
    '动物辅助治疗': 'Treatment',
    '社会支持': 'Treatment',
    '同伴支持': 'Treatment',
    '志愿支持': 'Treatment',
    '临终关怀': 'Treatment',
    '姑息治疗': 'Treatment',
    '安宁疗护': 'Treatment',
    '舒缓医疗': 'Treatment',
    'hospice': 'Treatment',
    ' advance care planning ': 'Treatment',
    'ACP': 'Treatment',
    '预立医疗指示': 'Treatment',
    '生前预嘱': 'Treatment',
    '症状控制': 'Treatment',
    '疼痛管理': 'Treatment',
    '呼吸困难管理': 'Treatment',
    '疲乏管理': 'Treatment',
    '恶病质': 'Treatment',
    '癌因性疲乏': 'Treatment',
    'CFS': 'Treatment',
    '睡眠障碍': 'Treatment',
    '焦虑抑郁': 'Treatment',
    '心理痛苦': 'Treatment',
    'DT': 'Treatment',
    '痛苦温度计': 'Treatment',
    '心理痛苦管理': 'Treatment',
    '灵性关怀': 'Treatment',
    '灵性痛苦': 'Treatment',
    '社会痛苦': 'Treatment',
    '存在痛苦': 'Treatment',
    '丧亲支持': 'Treatment',
    '哀伤辅导': 'Treatment',
    'bereavement': 'Treatment',
    '遗传咨询': 'Treatment',
    '基因检测': 'Treatment',
    '基因筛查': 'Treatment',
    '携带者筛查': 'Treatment',
    '新生儿筛查': 'Treatment',
    '产前诊断': 'Treatment',
    '植入前诊断': 'Treatment',
    'PGD': 'Treatment',
    'PGS': 'Treatment',
    'NIPT': 'Treatment',
    '精准医疗': 'Treatment',
    '个体化医疗': 'Treatment',
    '分层医疗': 'Treatment',
    '靶向治疗': 'Treatment',
    '免疫治疗': 'Treatment',
    '基因治疗': 'Treatment',
    '细胞治疗': 'Treatment',
    '干细胞移植': 'Treatment',
    'CAR-T': 'Treatment',
    'NK细胞': 'Treatment',
    '肿瘤疫苗': 'Treatment',
    '溶瘤病毒': 'Treatment',
    '光动力治疗': 'Treatment',
    'PDT': 'Treatment',
    '射频消融': 'Treatment',
    '微波消融': 'Treatment',
    '冷冻消融': 'Treatment',
    '不可逆电穿孔': 'Treatment',
    'IRE': 'Treatment',
    '海扶刀': 'Treatment',
    '质子治疗': 'Treatment',
    '重离子治疗': 'Treatment',
    '硼中子俘获治疗': 'Treatment',
    'BNCT': 'Treatment',
    '质子泵抑制剂': 'Medication',
    'PPI': 'Medication',
    'H2受体拮抗剂': 'Medication',
    '胃黏膜保护剂': 'Medication',
    '促胃肠动力药': 'Medication',
    '止泻药': 'Medication',
    '泻药': 'Medication',
    '益生菌制剂': 'Medication',
    '消化酶': 'Medication',
    '保肝药': 'Medication',
    '降酶药': 'Medication',
    '利胆药': 'Medication',
    '熊去氧胆酸': 'Medication',
    '腺苷蛋氨酸': 'Medication',
    '利尿剂': 'Medication',
    '袢利尿剂': 'Medication',
    '噻嗪类': 'Medication',
    '保钾利尿剂': 'Medication',
    '醛固酮拮抗剂': 'Medication',
    '强心苷': 'Medication',
    '地高辛': 'Medication',
    '西地兰': 'Medication',
    '磷酸二酯酶抑制剂': 'Medication',
    '米力农': 'Medication',
    '钙通道阻滞剂': 'Medication',
    'CCB': 'Medication',
    '氨氯地平': 'Medication',
    '硝苯地平': 'Medication',
    '非洛地平': 'Medication',
    '卡托普利': 'Medication',
    '依那普利': 'Medication',
    '贝那普利': 'Medication',
    '培哚普利': 'Medication',
    '氯沙坦': 'Medication',
    '缬沙坦': 'Medication',
    '替米沙坦': 'Medication',
    '厄贝沙坦': 'Medication',
    '沙库巴曲缬沙坦': 'Medication',
    '美托洛尔': 'Medication',
    '比索洛尔': 'Medication',
    '卡维地洛': 'Medication',
    '阿罗洛尔': 'Medication',
    '哌唑嗪': 'Medication',
    '特拉唑嗪': 'Medication',
    '多沙唑嗪': 'Medication',
    '硝酸甘油': 'Medication',
    '单硝酸异山梨酯': 'Medication',
    '消心痛': 'Medication',
    '阿司匹林': 'Medication',
    '氯吡格雷': 'Medication',
    '替格瑞洛': 'Medication',
    '普拉格雷': 'Medication',
    '华法林': 'Medication',
    '利伐沙班': 'Medication',
    '达比加群': 'Medication',
    '阿哌沙班': 'Medication',
    '艾多沙班': 'Medication',
    '尿激酶': 'Medication',
    '链激酶': 'Medication',
    'rt-PA': 'Medication',
    '阿替普酶': 'Medication',
    '阿托伐他汀': 'Medication',
    '瑞舒伐他汀': 'Medication',
    '辛伐他汀': 'Medication',
    '非诺贝特': 'Medication',
    '苯扎贝特': 'Medication',
    '依折麦布': 'Medication',
    'PCSK9抑制剂': 'Medication',
    '二甲双胍': 'Medication',
    '磺脲类': 'Medication',
    '格列本脲': 'Medication',
    '格列美脲': 'Medication',
    '瑞格列奈': 'Medication',
    '那格列奈': 'Medication',
    '阿卡波糖': 'Medication',
    '吡格列酮': 'Medication',
    '西格列汀': 'Medication',
    '沙格列汀': 'Medication',
    '达格列净': 'Medication',
    '恩格列净': 'Medication',
    '卡格列净': 'Medication',
    '利拉鲁肽': 'Medication',
    '司美格鲁肽': 'Medication',
    '度拉糖肽': 'Medication',
    '速效胰岛素': 'Medication',
    '短效胰岛素': 'Medication',
    '中效胰岛素': 'Medication',
    '长效胰岛素': 'Medication',
    '甘精胰岛素': 'Medication',
    '地特胰岛素': 'Medication',
    '德谷胰岛素': 'Medication',
    '预混胰岛素': 'Medication',
    '口服营养补充': 'Treatment',
    'ONS': 'Treatment',
    '肠内营养': 'Treatment',
    '肠外营养': 'Treatment',
    '营养支持': 'Treatment',
    '营养治疗': 'Treatment',
    '肺康复': 'Treatment',
    '呼吸康复': 'Treatment',
    '肺康复治疗': 'Treatment',
    '呼吸训练': 'Treatment',
    '肺移植': 'Treatment',
    '肺移植术': 'Treatment',
    '换肺': 'Treatment',
    '肺减容手术': 'Treatment',
    'LVRS': 'Treatment',
    '肺减容术': 'Treatment',
    '支气管镜肺减容术': 'Treatment',
    'BLVR': 'Treatment',
    '支气管镜肺减容': 'Treatment',
    '疫苗接种': 'Treatment',
    '预防接种': 'Treatment',
    '打疫苗': 'Treatment',
    '戒烟': 'Treatment',
    '禁烟': 'Treatment',
    '停止吸烟': 'Treatment',
    '戒除吸烟': 'Treatment',
    '氧疗': 'Treatment',
    '吸氧': 'Treatment',
    '氧气治疗': 'Treatment',
    '长期氧疗': 'Treatment',
    'LTOT': 'Treatment',
    '无创通气': 'Treatment',
    'NPPV': 'Treatment',
    'NIPPV': 'Treatment',
    '无创正压通气': 'Treatment',
    'BiPAP': 'Treatment',
    'CPAP': 'Treatment',
    '有创机械通气': 'Treatment',
    '机械通气': 'Treatment',
    '有创通气': 'Treatment',
    '呼吸机辅助通气': 'Treatment',
    '镇咳药物': 'Medication',
    '祛痰药': 'Medication',
    '化痰药': 'Medication',
    '黏液溶解剂': 'Medication',
    '黏液促排剂': 'Medication',
    '心理性咳嗽': 'Symptom',
    '难治性慢性咳嗽': 'Symptom',
    '急性咳嗽': 'Symptom',
    '慢性咳嗽病': 'Disease',
    '咳嗽变异性哮喘': 'Disease',
    '咳嗽变异性': 'Disease',
    '食管反流监测': 'Examination',
    '诱导痰细胞学检查': 'Examination',
    '气道黏液高分泌': 'Pathology',
    '肺脾气虚': 'TCM_Syndrome',
    '肺脾气虚证': 'TCM_Syndrome',
    '风寒袭肺': 'TCM_Syndrome',
    '风寒袭肺证': 'TCM_Syndrome',
    '气虚': 'TCM_Syndrome',
    '脉浮': 'TCM_Syndrome',
    '肺气虚': 'TCM_Syndrome',
    '肺阴虚': 'TCM_Syndrome',
    '脾气虚': 'TCM_Syndrome',
    '脾阳虚': 'TCM_Syndrome',
    '肾阴虚': 'TCM_Syndrome',
    '肾阳虚': 'TCM_Syndrome',
    '心气虚': 'TCM_Syndrome',
    '心阴虚': 'TCM_Syndrome',
    '肝气郁结': 'TCM_Syndrome',
    '肝火上炎': 'TCM_Syndrome',
    '肝阳上亢': 'TCM_Syndrome',
    '肝风内动': 'TCM_Syndrome',
    '痰热': 'TCM_Syndrome',
    '痰湿': 'TCM_Syndrome',
    '痰浊': 'TCM_Syndrome',
    '寒痰': 'TCM_Syndrome',
    '热痰': 'TCM_Syndrome',
    '燥痰': 'TCM_Syndrome',
    '风痰': 'TCM_Syndrome',
    '风热': 'TCM_Syndrome',
    '风寒': 'TCM_Syndrome',
    '风湿': 'TCM_Syndrome',
    '风热犯肺': 'TCM_Syndrome',
    '风寒袭肺': 'TCM_Syndrome',
    '燥热伤肺': 'TCM_Syndrome',
    '痰热壅肺': 'TCM_Syndrome',
    '肺脾气虚': 'TCM_Syndrome',
    '肺肾气虚': 'TCM_Syndrome',
    '肺肾阴虚': 'TCM_Syndrome',
    '脾肾阳虚': 'TCM_Syndrome',
    '心肾不交': 'TCM_Syndrome',
    '心脾两虚': 'TCM_Syndrome',
    '卫气': 'TCM_Syndrome',
    '营气': 'TCM_Syndrome',
    '宗气': 'TCM_Syndrome',
    '元气': 'TCM_Syndrome',
    '中气': 'TCM_Syndrome',
    '胃气': 'TCM_Syndrome',
    '肾气': 'TCM_Syndrome',
    '心气': 'TCM_Syndrome',
    '肝气': 'TCM_Syndrome',
    '六淫': 'TCM_Syndrome',
    '七情': 'TCM_Syndrome',
    '痰饮': 'TCM_Syndrome',
    '瘀血': 'TCM_Syndrome',
    '结石': 'TCM_Syndrome',
    '积食': 'TCM_Syndrome',
    '虫积': 'TCM_Syndrome',
    '风邪': 'TCM_Syndrome',
    '寒邪': 'TCM_Syndrome',
    '暑邪': 'TCM_Syndrome',
    '湿邪': 'TCM_Syndrome',
    '燥邪': 'TCM_Syndrome',
    '火邪': 'TCM_Syndrome',
    '热邪': 'TCM_Syndrome',
    '疫邪': 'TCM_Syndrome',
    '毒邪': 'TCM_Syndrome',
    '扶正': 'TCM_Syndrome',
    '祛邪': 'TCM_Syndrome',
    '攻补': 'TCM_Syndrome',
    '标本兼治': 'TCM_Syndrome',
    '治本': 'TCM_Syndrome',
    '治标': 'TCM_Syndrome',
    '活血化瘀': 'TCM_Syndrome',
    '理气化痰': 'TCM_Syndrome',
    '清热化痰': 'TCM_Syndrome',
    '温阳化饮': 'TCM_Syndrome',
    '健脾益气': 'TCM_Syndrome',
    '补肺益肾': 'TCM_Syndrome',
    '针灸': 'TCM_Syndrome',
    '艾灸': 'TCM_Syndrome',
    '拔罐': 'TCM_Syndrome',
    '刮痧': 'TCM_Syndrome',
    '推拿': 'TCM_Syndrome',
    '按摩': 'TCM_Syndrome',
    '导引': 'TCM_Syndrome',
    '气功': 'TCM_Syndrome',
    '汤剂': 'TCM_Syndrome',
    '散剂': 'TCM_Syndrome',
    '丸剂': 'TCM_Syndrome',
    '膏剂': 'TCM_Syndrome',
    '丹剂': 'TCM_Syndrome',
    '酒剂': 'TCM_Syndrome',
    '茶剂': 'TCM_Syndrome',
    '露剂': 'TCM_Syndrome',
    '锭剂': 'TCM_Syndrome',
    '中药': 'TCM_Syndrome',
    '西药': 'TCM_Syndrome',
    '草药': 'TCM_Syndrome',
    '饮片': 'TCM_Syndrome',
    '颗粒': 'TCM_Syndrome',
    '配方': 'TCM_Syndrome',
    '方剂': 'TCM_Syndrome',
    '药方': 'TCM_Syndrome',
    '君臣佐使': 'TCM_Syndrome',
    '主药': 'TCM_Syndrome',
    '辅药': 'TCM_Syndrome',
    '佐药': 'TCM_Syndrome',
    '使药': 'TCM_Syndrome',
    '剂量': 'TCM_Syndrome',
    '用法': 'TCM_Syndrome',
    '疗程': 'TCM_Syndrome',
    '禁忌': 'TCM_Syndrome',
    '慎用': 'TCM_Syndrome',
    '禁用': 'TCM_Syndrome',
    '忌用': 'TCM_Syndrome',
    '证候': 'TCM_Syndrome',
    '病机': 'TCM_Syndrome',
    '病位': 'TCM_Syndrome',
    '病性': 'TCM_Syndrome',
    '病势': 'TCM_Syndrome',
    '转归': 'TCM_Syndrome',
    '预后': 'TCM_Syndrome',
    '脉象': 'TCM_Syndrome',
    '舌象': 'TCM_Syndrome',
    '望诊': 'TCM_Syndrome',
    '闻诊': 'TCM_Syndrome',
    '问诊': 'TCM_Syndrome',
    '切诊': 'TCM_Syndrome',
    '同病异治': 'TCM_Syndrome',
    '异病同治': 'TCM_Syndrome',
    '辨证论治': 'TCM_Syndrome',
    '整体观念': 'TCM_Syndrome',
    '天人合一': 'TCM_Syndrome',
    '中药汤剂': 'TCM_Syndrome',
    '中药颗粒': 'TCM_Syndrome',
    '中药注射': 'TCM_Syndrome',
    '中成药': 'TCM_Syndrome',
    '院内制剂': 'TCM_Syndrome',
    '敷贴': 'TCM_Syndrome',
    '穴位': 'TCM_Syndrome',
    '经络': 'TCM_Syndrome',
    '腧穴': 'TCM_Syndrome',
    '募穴': 'TCM_Syndrome',
    '郄穴': 'TCM_Syndrome',
    '交会穴': 'TCM_Syndrome',
    '原穴': 'TCM_Syndrome',
    '络穴': 'TCM_Syndrome',
    '足三里': 'TCM_Syndrome',
    '三阴交': 'TCM_Syndrome',
    '肺俞': 'TCM_Syndrome',
    '脾俞': 'TCM_Syndrome',
    '肾俞': 'TCM_Syndrome',
    '膻中': 'TCM_Syndrome',
    '天突': 'TCM_Syndrome',
    '定喘': 'TCM_Syndrome',
    '膏肓': 'TCM_Syndrome',
    '大椎': 'TCM_Syndrome',
    '风门': 'TCM_Syndrome',
    '列缺': 'TCM_Syndrome',
    '太渊': 'TCM_Syndrome',
    '尺泽': 'TCM_Syndrome',
    '孔最': 'TCM_Syndrome',
    '中府': 'TCM_Syndrome',
    '云门': 'TCM_Syndrome',
    '合谷': 'TCM_Syndrome',
    '曲池': 'TCM_Syndrome',
    '内关': 'TCM_Syndrome',
    '外关': 'TCM_Syndrome',
    '神门': 'TCM_Syndrome',
    '通里': 'TCM_Syndrome',
    '阴郄': 'TCM_Syndrome',
    '少海': 'TCM_Syndrome',
    '太冲': 'TCM_Syndrome',
    '行间': 'TCM_Syndrome',
    '期门': 'TCM_Syndrome',
    '章门': 'TCM_Syndrome',
    '日月': 'TCM_Syndrome',
    '京门': 'TCM_Syndrome',
    '带脉': 'TCM_Syndrome',
    '环跳': 'TCM_Syndrome',
    '百会': 'TCM_Syndrome',
    '四神聪': 'TCM_Syndrome',
    '印堂': 'TCM_Syndrome',
    '太阳': 'TCM_Syndrome',
    '风池': 'TCM_Syndrome',
    '风府': 'TCM_Syndrome',
    '哑门': 'TCM_Syndrome',
    '迎香': 'TCM_Syndrome',
    '地仓': 'TCM_Syndrome',
    '颊车': 'TCM_Syndrome',
    '下关': 'TCM_Syndrome',
    '听宫': 'TCM_Syndrome',
    '翳风': 'TCM_Syndrome',
    '廉泉': 'TCM_Syndrome',
    '承浆': 'TCM_Syndrome',
    '人迎': 'TCM_Syndrome',
    '水突': 'TCM_Syndrome',
    '气舍': 'TCM_Syndrome',
    '缺盆': 'TCM_Syndrome',
    '极泉': 'TCM_Syndrome',
    '尺泽': 'TCM_Syndrome',
    '曲泽': 'TCM_Syndrome',
    '郄门': 'TCM_Syndrome',
    '间使': 'TCM_Syndrome',
    '内关': 'TCM_Syndrome',
    '大陵': 'TCM_Syndrome',
    '劳宫': 'TCM_Syndrome',
    '中冲': 'TCM_Syndrome',
    '少商': 'TCM_Syndrome',
    '鱼际': 'TCM_Syndrome',
    '太渊': 'TCM_Syndrome',
    '经渠': 'TCM_Syndrome',
    '列缺': 'TCM_Syndrome',
    '孔最': 'TCM_Syndrome',
    '尺泽': 'TCM_Syndrome',
    '侠白': 'TCM_Syndrome',
    '商阳': 'TCM_Syndrome',
    '二间': 'TCM_Syndrome',
    '三间': 'TCM_Syndrome',
    '合谷': 'TCM_Syndrome',
    '阳溪': 'TCM_Syndrome',
    '偏历': 'TCM_Syndrome',
    '温溜': 'TCM_Syndrome',
    '下廉': 'TCM_Syndrome',
    '隐白': 'TCM_Syndrome',
    '大都': 'TCM_Syndrome',
    '太白': 'TCM_Syndrome',
    '公孙': 'TCM_Syndrome',
    '商丘': 'TCM_Syndrome',
    '三阴交': 'TCM_Syndrome',
    '漏谷': 'TCM_Syndrome',
    '地机': 'TCM_Syndrome',
    '阴陵泉': 'TCM_Syndrome',
    '血海': 'TCM_Syndrome',
    '箕门': 'TCM_Syndrome',
    '冲门': 'TCM_Syndrome',
    '府舍': 'TCM_Syndrome',
    '腹结': 'TCM_Syndrome',
    '大横': 'TCM_Syndrome',
    '腹哀': 'TCM_Syndrome',
    '天池': 'TCM_Syndrome',
    '天泉': 'TCM_Syndrome',
    '曲泽': 'TCM_Syndrome',
    '郄门': 'TCM_Syndrome',
    '间使': 'TCM_Syndrome',
    '内关': 'TCM_Syndrome',
    '大陵': 'TCM_Syndrome',
    '劳宫': 'TCM_Syndrome',
    '极泉': 'TCM_Syndrome',
    '青灵': 'TCM_Syndrome',
    '少海': 'TCM_Syndrome',
    '灵道': 'TCM_Syndrome',
    '通里': 'TCM_Syndrome',
    '阴郄': 'TCM_Syndrome',
    '神门': 'TCM_Syndrome',
    '少府': 'TCM_Syndrome',
    '少冲': 'TCM_Syndrome',
    '少泽': 'TCM_Syndrome',
    '前谷': 'TCM_Syndrome',
    '后溪': 'TCM_Syndrome',
    '腕骨': 'TCM_Syndrome',
    '阳谷': 'TCM_Syndrome',
    '养老': 'TCM_Syndrome',
    '支正': 'TCM_Syndrome',
    '涌泉': 'TCM_Syndrome',
    '然谷': 'TCM_Syndrome',
    '太溪': 'TCM_Syndrome',
    '大钟': 'TCM_Syndrome',
    '水泉': 'TCM_Syndrome',
    '照海': 'TCM_Syndrome',
    '复溜': 'TCM_Syndrome',
    '交信': 'TCM_Syndrome',
    '筑宾': 'TCM_Syndrome',
    '阴谷': 'TCM_Syndrome',
    '横骨': 'TCM_Syndrome',
    '大赫': 'TCM_Syndrome',
    '气穴': 'TCM_Syndrome',
    '四满': 'TCM_Syndrome',
    '中注': 'TCM_Syndrome',
    '肓俞': 'TCM_Syndrome',
    '商曲': 'TCM_Syndrome',
    '石关': 'TCM_Syndrome',
    '阴都': 'TCM_Syndrome',
    '腹通谷': 'TCM_Syndrome',
    '幽门': 'TCM_Syndrome',
    '步廊': 'TCM_Syndrome',
    '神封': 'TCM_Syndrome',
    '灵墟': 'TCM_Syndrome',
    '神藏': 'TCM_Syndrome',
    '彧中': 'TCM_Syndrome',
    '俞府': 'TCM_Syndrome',
    '瞳子髎': 'TCM_Syndrome',
    '听会': 'TCM_Syndrome',
    '上关': 'TCM_Syndrome',
    '颔厌': 'TCM_Syndrome',
    '悬颅': 'TCM_Syndrome',
    '悬厘': 'TCM_Syndrome',
    '曲鬓': 'TCM_Syndrome',
    '率谷': 'TCM_Syndrome',
    '天冲': 'TCM_Syndrome',
    '浮白': 'TCM_Syndrome',
    '头窍阴': 'TCM_Syndrome',
    '完骨': 'TCM_Syndrome',
    '本神': 'TCM_Syndrome',
    '阳白': 'TCM_Syndrome',
    '头临泣': 'TCM_Syndrome',
    '目窗': 'TCM_Syndrome',
    '正营': 'TCM_Syndrome',
    '承灵': 'TCM_Syndrome',
    '脑空': 'TCM_Syndrome',
    '风池': 'TCM_Syndrome',
    '肩井': 'TCM_Syndrome',
    '渊腋': 'TCM_Syndrome',
    '辄筋': 'TCM_Syndrome',
    '日月': 'TCM_Syndrome',
    '京门': 'TCM_Syndrome',
    '带脉': 'TCM_Syndrome',
    '五枢': 'TCM_Syndrome',
    '维道': 'TCM_Syndrome',
    '居髎': 'TCM_Syndrome',
    '环跳': 'TCM_Syndrome',
    '风市': 'TCM_Syndrome',
    '中渎': 'TCM_Syndrome',
    '膝阳关': 'TCM_Syndrome',
    '阳陵泉': 'TCM_Syndrome',
    '阳交': 'TCM_Syndrome',
    '外丘': 'TCM_Syndrome',
    '光明': 'TCM_Syndrome',
    '阳辅': 'TCM_Syndrome',
    '悬钟': 'TCM_Syndrome',
    '丘墟': 'TCM_Syndrome',
    '足临泣': 'TCM_Syndrome',
    '地五会': 'TCM_Syndrome',
    '侠溪': 'TCM_Syndrome',
    '足窍阴': 'TCM_Syndrome',
    '大敦': 'TCM_Syndrome',
    '行间': 'TCM_Syndrome',
    '太冲': 'TCM_Syndrome',
    '中封': 'TCM_Syndrome',
    '蠡沟': 'TCM_Syndrome',
    '中都': 'TCM_Syndrome',
    '膝关': 'TCM_Syndrome',
    '曲泉': 'TCM_Syndrome',
    '阴包': 'TCM_Syndrome',
    '足五里': 'TCM_Syndrome',
    '阴廉': 'TCM_Syndrome',
    '急脉': 'TCM_Syndrome',
    '章门': 'TCM_Syndrome',
    '期门': 'TCM_Syndrome',
    '长强': 'TCM_Syndrome',
    '腰俞': 'TCM_Syndrome',
    '腰阳关': 'TCM_Syndrome',
    '命门': 'TCM_Syndrome',
    '悬枢': 'TCM_Syndrome',
    '脊中': 'TCM_Syndrome',
    '中枢': 'TCM_Syndrome',
    '筋缩': 'TCM_Syndrome',
    '至阳': 'TCM_Syndrome',
    '灵台': 'TCM_Syndrome',
    '神道': 'TCM_Syndrome',
    '身柱': 'TCM_Syndrome',
    '陶道': 'TCM_Syndrome',
    '大椎': 'TCM_Syndrome',
    '哑门': 'TCM_Syndrome',
    '风府': 'TCM_Syndrome',
    '脑户': 'TCM_Syndrome',
    '强间': 'TCM_Syndrome',
    '后顶': 'TCM_Syndrome',
    '百会': 'TCM_Syndrome',
    '前顶': 'TCM_Syndrome',
    '囟会': 'TCM_Syndrome',
    '上星': 'TCM_Syndrome',
    '神庭': 'TCM_Syndrome',
    '素髎': 'TCM_Syndrome',
    '水沟': 'TCM_Syndrome',
    '兑端': 'TCM_Syndrome',
    '龈交': 'TCM_Syndrome',
    '四神聪': 'TCM_Syndrome',
    '当阳': 'TCM_Syndrome',
    '安眠': 'TCM_Syndrome',
    '牵正': 'TCM_Syndrome',
    '翳明': 'TCM_Syndrome',
    '颈百劳': 'TCM_Syndrome',
    '定喘': 'TCM_Syndrome',
    '夹脊': 'TCM_Syndrome',
    '胃脘下俞': 'TCM_Syndrome',
    '痞根': 'TCM_Syndrome',
    '下极俞': 'TCM_Syndrome',
    '腰宜': 'TCM_Syndrome',
    '腰眼': 'TCM_Syndrome',
    '十七椎': 'TCM_Syndrome',
    '十宣': 'TCM_Syndrome',
    '四缝': 'TCM_Syndrome',
    '中魁': 'TCM_Syndrome',
    '八邪': 'TCM_Syndrome',
    '大骨空': 'TCM_Syndrome',
    '小骨空': 'TCM_Syndrome',
    '腰痛点': 'TCM_Syndrome',
    '外劳宫': 'TCM_Syndrome',
    '二白': 'TCM_Syndrome',
    '肘尖': 'TCM_Syndrome',
    '中泉': 'TCM_Syndrome',
    '八风': 'TCM_Syndrome',
    '独阴': 'TCM_Syndrome',
    '气端': 'TCM_Syndrome',
    '里内庭': 'TCM_Syndrome',
    '阑尾': 'TCM_Syndrome',
    '胆囊': 'TCM_Syndrome',
    '膝眼': 'TCM_Syndrome',
    '百虫窝': 'TCM_Syndrome',
    '鹤顶': 'TCM_Syndrome',
    '内膝眼': 'TCM_Syndrome',
    '外膝眼': 'TCM_Syndrome',
    '髋骨': 'TCM_Syndrome',
    '陵后': 'TCM_Syndrome',
    '陵下': 'TCM_Syndrome',
    '膝旁': 'TCM_Syndrome',
    '成骨': 'TCM_Syndrome',
    '太阴': 'TCM_Syndrome',
    '少阳维': 'TCM_Syndrome',
    '委上': 'TCM_Syndrome',
    '营池': 'TCM_Syndrome',
    '太阳': 'TCM_Syndrome',
    '太阴': 'TCM_Syndrome',
    '少阳': 'TCM_Syndrome',
    '阳明': 'TCM_Syndrome',
    '厥阴': 'TCM_Syndrome',
    '少阴': 'TCM_Syndrome',
    '太阳病': 'TCM_Syndrome',
    '阳明病': 'TCM_Syndrome',
    '少阳病': 'TCM_Syndrome',
    '太阴病': 'TCM_Syndrome',
    '少阴病': 'TCM_Syndrome',
    '厥阴病': 'TCM_Syndrome',
    '表证': 'TCM_Syndrome',
    '里证': 'TCM_Syndrome',
    '寒证': 'TCM_Syndrome',
    '热证': 'TCM_Syndrome',
    '虚证': 'TCM_Syndrome',
    '实证': 'TCM_Syndrome',
    '阴证': 'TCM_Syndrome',
    '阳证': 'TCM_Syndrome',
    '气虚': 'TCM_Syndrome',
    '血虚': 'TCM_Syndrome',
    '阴虚': 'TCM_Syndrome',
    '阳虚': 'TCM_Syndrome',
    '气滞': 'TCM_Syndrome',
    '血瘀': 'TCM_Syndrome',
    '痰饮': 'TCM_Syndrome',
    '水湿': 'TCM_Syndrome',
    '湿热': 'TCM_Syndrome',
    '寒湿': 'TCM_Syndrome',
}


def main():
    print("=" * 60)
    print("全部中文文献种子词典最终清理")
    print("=" * 60)

    with open(INPUT_TSV, 'r', encoding='utf-8') as f:
        lines = f.readlines()[1:]

    entries = []
    for line in lines:
        parts = line.strip().split('\t')
        if len(parts) >= 9:
            entries.append({
                'rank': parts[0],
                'standard': parts[1],
                'aliases': parts[2] if parts[2] != '-' else '',
                'type': parts[3],
                'freq': int(parts[4]),
                'title': int(parts[5]),
                'bold': int(parts[6]),
                'table': int(parts[7]),
                'score': float(parts[8]),
            })

    print(f"输入: {len(entries)} 条")

    # 步骤1: 删除黑名单
    cleaned = []
    deleted = []
    for e in entries:
        std = e['standard']
        if std in BLACKLIST:
            deleted.append((std, '黑名单'))
            continue
        # 截断检测
        if std[-1] in {'的', '存', '助', '查', '疗', '治', '用', '作', '法', '例', '态', '型', '式', '类', '种', '因', '为', '及', '与', '或', '但', '而', '在', '对', '给', '让', '使', '叫', '令', '来', '去', '上', '下', '中', '内', '外', '前', '后', '里', '间', '旁', '侧', '头', '部', '面', '方', '极', '太', '很', '好', '大', '小', '多', '少', '高', '低', '长', '短', '快', '慢', '早', '晚', '新', '旧', '轻', '重', '强', '弱', '深', '浅', '近', '远', '冷', '热', '干', '湿', '软', '硬', '松', '紧', '清', '浊', '纯', '杂', '浓', '淡', '香', '臭', '甜', '苦', '酸', '辣', '咸', '鲜', '涩', '滑', '糙', '粘', '稠', '稀', '薄', '厚', '粗', '细', '宽', '窄', '密', '疏', '整', '碎', '完', '缺', '全', '残', '正', '歪', '直', '弯', '平', '斜', '凸', '凹', '圆', '扁', '尖', '钝', '锐', '秃', '毛', '光', '暗', '明', '亮', '黑', '白', '红', '黄', '蓝', '绿', '青', '紫', '灰', '粉', '棕', '褐', '橙', '赤', '朱'}:
            deleted.append((std, '截断词'))
            continue
        cleaned.append(e)

    print(f"黑名单/截断过滤后: {len(cleaned)} 条")
    print(f"删除: {len(deleted)} 条")

    # 步骤2: 修正类型
    for e in cleaned:
        std = e['standard']
        if std in TYPE_FIX:
            e['type'] = TYPE_FIX[std]

    # 步骤3: 删除Concept类型中得分过低或明显非医学的条目
    final = []
    concept_noise = []
    for e in cleaned:
        if e['type'] == 'Concept' and (e['score'] < 60 or len(e['standard']) <= 3):
            # 保留一些高分的Concept
            if e['score'] < 80:
                concept_noise.append(e)
                continue
        final.append(e)

    print(f"Concept噪声过滤后: {len(final)} 条")
    print(f"  过滤Concept噪声: {len(concept_noise)} 条")

    # 步骤4: 重新排序（按类型分组，同类型内按得分排序）
    TYPE_ORDER = ['Disease', 'Symptom', 'Examination', 'Medication', 'Treatment',
                  'Pathology', 'Complication', 'RiskFactor', 'Guideline',
                  'Organization', 'TCM_Syndrome', 'Concept', 'Anatomical']
    final.sort(key=lambda x: (TYPE_ORDER.index(x['type']) if x['type'] in TYPE_ORDER else 99, -x['score']))
    for i, e in enumerate(final, 1):
        e['rank'] = i

    print(f"\n最终: {len(final)} 条")

    # 类型统计
    type_counts = {}
    for e in final:
        t = e['type']
        type_counts[t] = type_counts.get(t, 0) + 1

    print("\n类型分布:")
    for t in TYPE_ORDER:
        if t in type_counts:
            print(f"  {t:<14} : {type_counts[t]:>3} 条")

    # 保存
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 1) TSV
    tsv_path = os.path.join(OUTPUT_DIR, '28_全部中文文献_最终种子词典_已清理.tsv')
    with open(tsv_path, 'w', encoding='utf-8') as f:
        f.write("排名\t标准术语\t同义词\t类型\t总频次\t标题\t加粗\t表格\t得分\n")
        for e in final:
            alias = e['aliases'] if e['aliases'] else '-'
            f.write(f"{e['rank']}\t{e['standard']}\t{alias}\t{e['type']}\t"
                    f"{e['freq']}\t{e['title']}\t{e['bold']}\t{e['table']}\t{e['score']:.1f}\n")

    # 2) JSON
    json_path = os.path.join(OUTPUT_DIR, '28_全部中文文献_最终种子词典.json')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(final, f, ensure_ascii=False, indent=2)

    # 3) 按类型分组
    TYPE_LABELS = {
        'Disease': '疾病', 'Symptom': '症状体征', 'Examination': '检查检验',
        'Medication': '药物', 'Treatment': '治疗方法', 'Pathology': '病理机制',
        'Complication': '并发症', 'RiskFactor': '危险因素', 'Guideline': '指南标准',
        'Organization': '组织机构', 'TCM_Syndrome': '中医证候', 'Concept': '抽象概念',
        'Anatomical': '解剖部位',
    }
    grouped_path = os.path.join(OUTPUT_DIR, '28_全部中文文献_最终种子词典_按类型分组.txt')
    with open(grouped_path, 'w', encoding='utf-8') as f:
        for t in TYPE_ORDER:
            items = [e for e in final if e['type'] == t]
            if not items:
                continue
            f.write(f"\n{'='*50}\n")
            f.write(f"【{TYPE_LABELS[t]} / {t}】({len(items)}条)\n")
            f.write(f"{'='*50}\n")
            for e in items:
                alias = f" ({e['aliases']})" if e['aliases'] else ""
                f.write(f"  - {e['standard']}{alias}\n")

    # 4) 标准词表
    wordlist_path = os.path.join(OUTPUT_DIR, '28_全部中文文献_最终种子词典.txt')
    with open(wordlist_path, 'w', encoding='utf-8') as f:
        for e in final:
            f.write(e['standard'] + '\n')

    # 5) 含同义词
    full_path = os.path.join(OUTPUT_DIR, '28_全部中文文献_最终种子词典_含同义词.txt')
    with open(full_path, 'w', encoding='utf-8') as f:
        for e in final:
            line = e['standard']
            if e['aliases']:
                line += ' | ' + ' | '.join(e['aliases'].split('、'))
            f.write(line + '\n')

    print(f"\n[已保存]")
    print(f"  最终TSV: {tsv_path}")
    print(f"  JSON: {json_path}")
    print(f"  按类型分组: {grouped_path}")
    print(f"  标准词表: {wordlist_path}")
    print(f"  含同义词: {full_path}")

    # 预览
    print("\n" + "=" * 70)
    print("Top 50 最终种子词典")
    print("=" * 70)
    print(f"{'排名':<4} {'标准术语':<22} {'类型':<10} {'同义词':<18} {'频次':<5} {'得分':<6}")
    print("-" * 70)
    for e in final[:50]:
        alias = e['aliases'][:16] if e['aliases'] else '-'
        print(f"{e['rank']:<4} {e['standard']:<22} {e['type']:<10} {alias:<18} {e['freq']:<5} {e['score']:<6.1f}")


if __name__ == '__main__':
    main()
